### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [sbeltran10/moncrud#2]
Hi @sbeltran10 I am a logo designer.

i contribute by designing logos to open source community. I think this repo does not have a logo. So i designed a logo for the repo. What do you think?

![moncrud](https://user-images.githubusercontent.com/36298335/57183610-15c85880-6eb8-11e9-9538-dc85ed274402.jpg)

**Comment by sbeltran10** [comment]
Hi @reallinfo, thank you for this design!

I think the logo looks great and I like how you combined the management, view and mongo "concepts" to design it, because that is exactly what I would think is the best way to conceive what MonCRUD does. And, as matter of fact, I plan to release the first public usable version within the next 2 weeks so this logo  will look great in the docs and demo page.

Once again, I really appreciate it

**Comment by reallinfo** [comment]
You're welcome! I will send a pr if you don't have any other request me.

**Comment by sbeltran10** [comment]
Alright, thank you once again
